#define BACKEND_SOCKET "ipc://backend"          // used by the query handler
#define ENV_LOG_TARGET_SOCKET "JOURNAL_REMOTE_TARGET"
#define ENV_JOURNAL_SOURCE_DIRECTORY "JOURNAL_SOURCE_DIR"
#define ENV_SINCE_TIMESTAMP "JOURNAL_EXPORT_FROM"
#define ENV_UNTIL_TIMESTAMP "JOURNAL_EXPORT_TO"
#define ENV_BOOT "JOURNAL_EXPORT_BOOT_ID"
